on: [push]

jobs:
  build_container_with_docker:
    runs-on: ubuntu-latest
    name: Build container with Docker
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build docker image and run a smoke test
      id: build_docker_image
      run: |
        docker build -f Dockerfile -t warp:latest .
        docker run -d -p 5000:5000 --name warp warp:latest
        sleep 10
        docker rm -f warp
